### ISSUE TITLE
"Can't accept unmodified entity" exception when trying to push data

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#304] opened 2017-08-29 11:49 UTC

**Comment by MartinWahnschaffeSymeda** [comment] 2017-09-04 07:50
Error goes along with 

> DaoException  - Root cause: de.symeda.sormas.app.backend.common.DaoException: Change  date does not match. Looks like sync was done between reading and saving  the entity

Happens when a case is pushed. It's probably an entry in the previous hospitalizations or epi travels/burials that should actually be set to modifed, but isn't.

>  java.util.concurrent.ThreadPoolExecutor$Worker:run:607 
>  java.lang.Thread:run:761 - Root cause stack trace: de.symeda.sormas.app.backend.common.AbstractAdoDao:accept:649 
>  de.symeda.sormas.app.backend.common.AbstractAdoDao:acceptWithCast:635 
>  de.symeda.sormas.app.backend.common.AbstractAdoDao:accept:663 
>  de.symeda.sormas.app.backend.common.AbstractAdoDao:acceptWithCast:635 
>  de.symeda.sormas.app.backend.common.AbstractAdoDao:accept:700 
>  de.symeda.sormas.app.backend.common.AdoDtoHelper$2:call:129 
>  de.symeda.sormas.app.backend.common.AdoDtoHelper$2:call:125

**Comment by MartinWahnschaffeSymeda** [comment] 2017-09-04 08:01
Bug was caused by previous hospitalizations not correctly being loaded and synchronized in the app.
Was fixed in 7a3306a

**Closed by MartinWahnschaffeSymeda** 2017-09-04 08:01 UTC
Labels: bug
