### ISSUE TITLE
Error on map

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#447] opened 2017-12-13 08:53 UTC
![image](https://user-images.githubusercontent.com/19344651/33929919-71986392-dfeb-11e7-97b2-52c8e1f044a1.png)
@MartinWahnschaffeSymeda @MateStrysewskeSym

**Comment by hzi-braunschweig** [comment] 2017-12-13 08:54
@MartinWahnschaffeSymeda @MateStrysewskeSym  it happens when you click case incidence

**Comment by hzi-braunschweig** [comment] 2017-12-13 08:55
@MartinWahnschaffeSymeda  infact for all

![image](https://user-images.githubusercontent.com/19344651/33930005-c1dd2450-dfeb-11e7-8c09-ef3ece279eef.png)

**Comment by MateStrysewskeSym** [comment] 2017-12-13 08:59
@hzi-braunschweig I'll have a look at that right now.

**Comment by MateStrysewskeSym** [comment] 2017-12-13 10:11
This error is caused by missing population data in the database which, in turn, is probably the result of a failed data import for certain districts. For now, the population of these districts has been set to 100,000 temporarily to get rid of the error.

Things to do:

- [ ] Code fix: Make sure the system can handle districts without a population
- [ ] Code fix: Make sure that no ArithmeticException is thrown when the population number is too low
- [ ] Find the source of the problem described above and fix it

**Comment by MartinWahnschaffeSymeda** [comment] 2017-12-18 16:51
Query for locations, cases, previous hospitalizations and users assigned to obsolete districts:

>   SELECT location.id, district.id, district.name, community.id, community.name FROM location
>   JOIN district ON district.id = district_id
>   LEFT JOIN community ON community.id = community_id
>   WHERE district.epidcode IS NULL;
> 
>   SELECT cases.id, district.id, district.name, community.id, community.name, facility.id, facility.name FROM cases
>   JOIN district ON district.id = district_id
>   LEFT JOIN community ON community.id = community_id
>   LEFT JOIN facility ON facility.id = healthfacility_id
>   WHERE district.epidcode IS NULL;
>   
>   SELECT previoushospitalization.id, district.id, district.name, community.id, community.name, facility.id, facility.name FROM previoushospitalization
>   JOIN district ON district.id = district_id
>   LEFT JOIN community ON community.id = community_id
>   LEFT JOIN facility ON facility.id = healthfacility_id
>   WHERE district.epidcode IS NULL;
> 
>   SELECT users.id, users.username, district.id, district.name, facility.id, facility.name FROM users
>   JOIN district ON district.id = district_id
>   LEFT JOIN facility ON facility.id = healthfacility_id
>   WHERE district.epidcode IS NULL;
> 
>   DELETE FROM facility WHERE district_id IN (SELECT id FROM district WHERE epidcode IS NULL);
>   DELETE FROM community WHERE district_id IN (SELECT id FROM district WHERE epidcode IS NULL);
>   DELETE FROM district WHERE epidcode IS NULL;

sormas.org.ng - also set the change date
location:

> 	137475;129185;"Afijio LGA";129181;"Ilora II Ward" -> d:142405; c:142538 -> set change date for person 137474 
> 	137477;129185;"Afijio LGA";129175;" Ilora 1 Ward" -> d:142405; c:142532 
> 	139151;129254;"Ibadan North LGA";129248;"Bodija  Ward" -> d:142410; c:142588 -> set change date for person 139150 

cases:

> 	139152;129254;"Ibadan North LGA";129248;"Bodija  Ward";129821;"University College Hospital" -> d:142410; c:142588; f:143151

users:

> 	136776;"oyo2";129185;"Afijio LGA";129571;"Aba-Adio Primary Health Centre" -> d:142405; f:142916
> 	136774;"oyo3";129185;"Afijio LGA";;"" -> d:142405
> 	136772;"oyooyo4";129185;"Afijio LGA";;"" -> d:142405

renamed Yewa North/Sourth to Egbado North/South

**Closed** 2017-12-18 16:51 UTC
Labels: bug, important
