### ISSUE TITLE
person data bug when creating new case (app)

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#130] opened 2017-02-24 15:20 UTC
create new case, enter all person data, save 
-> data disappears; crashes if you hit save again

**Comment by MateStrysewskeSym** [comment] 2017-03-01 07:44
@MartinWahnschaffeSymeda please verify that this bug still exists for you, because I can't reproduce it.

**Comment by MateStrysewskeSym** [comment] 2017-03-01 12:43
Probably fixed with #118

**Closed by MateStrysewskeSym** 2017-03-01 12:43 UTC
Labels: accepted, bug, Case Surveillance, sormas-app
