### ISSUE TITLE
Task execution buttons don't show

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#257] opened 2017-07-31 10:04 UTC
To Reproduce try to use two phones: Report a new case with the informant and see if the officer gets the task and can execute it.

**Comment by MateStrysewskeSym** [comment] 2017-08-03 10:34
We couldn't reproduce this error; it might have been already fixed, but just to make sure, I'm moving this to Sprint 23 in case it reoccurs.

**Comment by MartinWahnschaffeSymeda** [comment] 2017-08-11 12:51
Happened with Informant on my emulator

**Closed** 2017-08-15 08:05 UTC
Labels: bug, sormas-app
