### ISSUE TITLE
Case fatality rates calculations for the dashboard [2]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#535] opened 2018-03-22 15:22 UTC
@MateStrysewskeSym @MartinWahnschaffeSymeda 

Most preferred approach will be to compute case fatality rate for the following as a filter on the dashboard:
- [ ] numerator is confirmed cases  ( denominator is confirmed cases for fatalities)
- [ ] numerator is confirmed and probable cases ( confirmed and probable fatalities as denominator)
- [ ] numerator is confirmed suspected and probable cases ( all fatalities excluding not yet classified and not a case)

Epidemic disease for cause of death filter should not be used. Please mirror the default disease in question in the drop down instead.

**Comment by MateStrysewskeSym** [comment] 2018-03-23 06:23
@hzi-braunschweig "Epidemic disease for cause of death filter should not be used. Please mirror the default disease in question in the drop down instead." - what do you mean by that? We don't have a cause of death filter on the Dashboard right now.

**Comment by hzi-braunschweig** [comment] 2018-03-23 07:03
@MateStrysewskeSym I was referring to the present condition (dead) which is usd to calculate fatalities for the dashboard. do you get what I mean now? see screenshot below
![image](https://user-images.githubusercontent.com/19344651/37815775-8e6b396c-2e70-11e8-8dfa-84bfa3de4729.png)

**Comment by MateStrysewskeSym** [comment] 2018-03-23 07:06
@hzi-braunschweig Still not a hundred percent, actually. We don't take the disease specified under "Cause of death" into account when calculating the CFR, if that's what you mean. The only interesting thing is how many cases that have the disease selected on the Dashboard have died, irrespective of the cause of their death. Does that match your request?

**Comment by hzi-braunschweig** [comment] 2018-03-23 07:25
@MateStrysewskeSym @MartinWahnschaffeSymeda @Krisistis 

In epidemiology, a case fatality rate (CFR)—or case fatality risk, case fatality ratio or just fatality rate—is the proportion of deaths within a designated population of "cases" (people with a medical condition), over the course of the disease.

Case fatality rate is calculated by dividing the number of deaths from a specified disease over a defined period of time by the number of individuals diagnosed with the disease during that time; the resulting ratio is then multiplied by 100 to yield a percentage.

The problem with calculating the CFR with fatalities irrespective of the cause of death will not be correct because CFR is usually calculated to actually know the exact impact of the disease to kill. For instance, Of course, we all agree that it is the “most correct” way to calculate the case fatality rate as the ratio of confirmed death and confirmed cases. 
But: We had a look at the database yesterday: For Lassa it is very correct that we might underestimate the fatality rate if we include all not confirmed cases. In contrast, if we exclude all not confirmed cases for CSM, we will likely underestimate the fatality rate, as most (or at least very many) of the dead people are not confirmed.
 it is an option to adapt disease specific and also to adapt during the course of an outbreak (e.g. because there is not enough lab capacity for tests in the beginning, more lab tests are conducted later through international support). I guess it is most important to clarify (e.g. through a disclaimer) how the calculation is done. Another option, which came up already yesterday, is that we offer cases and deaths by status. This would offer the possibility for epidemiologists to calculate the fatality rate they find most appropriate. But in this context it might happen that different fatality rates circle in the public and we should think of targeting a rate, which should be communicated to the public.

But on the dashboard, Gerard said he would prefer 3 options on the dashboard which shows:
-[ ] numerator is confirmed cases ( denominator is confirmed cases for fatalities)
-[ ] numerator is confirmed and probable cases ( confirmed and probable fatalities as denominator)
-[ ] numerator is confirmed suspected and probable cases ( all fatalities excluding not yet classified and not a case)
You need to use the present condition (dead) and cause of death variable to be able to filter the denominator and numerator accordingly. And please instead of epidemic disease which refers to the default disease in question, use the actual name of the disease in question in the dropdown. Then when you want to calculate:

-[ ] Number of confirmed cases divided by number of confirmed deaths (CFR) use as denominator only deaths that were due to the "epidemic disease" in this case use the actual disease
-[ ] Number of confirmed and probable cases divided by number of confirmed and probable deaths (CFR) use as denominator only deaths that were due to the sum of confirmed and probable cases of the specified disease
-[ ] Number of confirmed, suspected and probable cases divided by number of confirmed, suspected and probable deaths (CFR) use as denominator all deaths that were due to the sum of confirmed, suspected and probable cases of the specified disease excluding" not yet classified cases" and "not a case"

is this clear? If not, please explain which variables you use to calculate the CFR.

Thanks

**Comment by MateStrysewskeSym** [comment] 2018-03-23 08:02
@hzi-braunschweig We specifically added two dropdowns to the Person view because a person might have different cases. If a person with both an EVD and a CSM case dies, it's necessary to specify which disease likely caused the death, which is why you have to choose the disease in question when specifying the cause. Whenever you select "epidemic disease" in the first dropdown, the second dropdown will appear right next to it where you will be able to select the disease which, by the way, already pre-selects the disease of the currently opened case.

Now on to the calculations; the way it's currently done is that we retrieve all new cases of the selected disease in the specified time frame (based on onset date -> reception date -> report date), check the status of the associated persons and then calculate the CFR based on the number of deceased persons in relation to the number of confirmed cases. However, the cause of death field is currently ignored as this was never part of the specification yet.

What I understand you need us to do is to instead take the cause of death into account and only count the cases that have actually died because of the disease in question; which means that someone who has died but due to another reason would be excluded from this statistic.

**Comment by hzi-braunschweig** [comment] 2018-03-28 17:59
@MateStrysewskeSym @MartinWahnschaffeSymeda 

From @Gerard

CFR is generally indeed calculated by using the total number of cases (confirmed, and probably and suspect), for the very reasons described by Kristin below.

And also in agreement with Kristin – ideally one would have a default CFR figure based on the approach above but an option to calculate it with another denominator eg only confirmed or only confirmed and probable) 


So simple and quick solution : use all cases including suspect, confirmed and probable as denominator

**Comment by MartinWahnschaffeSymeda** [comment] 2018-04-04 13:04
@hzi-braunschweig The current CFR calcuation is likely not correct. We have to discuss how the time filter should be working for the calcuation.

Example: time periof from epi week 13 to 14.
Nominator: number of cases that died from the disease within these two weeks. What about cases that are related to the same outbreak but died a few days or weeks before?
Denominator: number of cases active in this period. Included all cases that were created in the period or died withing the period.

I suggest to have a phone call on this. Maybe also incorporating Gérard or Juliane.

**Comment by MartinWahnschaffeSymeda** [comment] 2018-04-11 13:17
From @gerard

If you are still in the first reporting week the CFR for Kano for the first week would be 10%, because you do not know yet that the other two patients will also die. 

As you update the CFR at the end of the second reporting week CFR for the first week will be 30%, because by now you know that two additional patients originally notified in Kano state during that first week have in the meanwhile died.

If a fourth patient would would be originally detected and notified in a neighboring state in week one and transferred to a hospital in Kano state where that patient would eventually die, this fatality would NOT augment the CFR of Kano state, even though the patient died there , for the simple reason, because that case belongs notification-wise to the neighboring state. 

It is an important principle in surveillance to keep place an time in mind and to relate both to the notification, regardless where the patient originally came from or when the patient actually died. 

This principle applies also for many other analyses and statistics (hospitalizations, etc etc) in surveillance and epidemiology. 

As I keep saying in my lectures „ a good epidemiologist always must have the proper denominator in his pocket“ this is also why I put so much importance on getting proper and highly stratified population data. 

I hope my explanations are clear and many we do not need a telco anymore.

It is important that such Formulars are well documented and easily findable in the sormas manual. Maybe also in the website we should open a special section „key definitions and Formulars used  in sormas“
 
@Juliane, can you please take care of this aspect in manual and website and put it on the to do list of pm?

**Closed** 2018-04-13 06:38 UTC
Labels: 102XX, Dashboard, sormas-ui
