### ISSUE TITLE
Bulk operations

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#443] opened 2017-12-06 16:18 UTC
@MartinWahnschaffeSymeda @MateStrysewskeSym 
We need to be able to perform bulk operations like multi-select to delete, move or assign tasks, Please lets think about this.

Thanks

**Comment by MartinWahnschaffeSymeda** [comment] 2017-12-07 13:14
Duplicate of #411

**Closed by MartinWahnschaffeSymeda** 2017-12-07 13:14 UTC
Labels: duplicate
